### ISSUE TITLE
AssertionError: infinite loop

### ISSUE THREAD

**Issue by martin-sucha** [pyconsk/snakepit-game#1]
Hi,

just got the following exception:

```
Traceback (most recent call last):
  File "<snip>/snakepit/server.py", line 129, in game_loop
    await game.next_frame()
  File "<snip>/snakepit/game.py", line 393, in next_frame
    assert first_player_loop, 'infinite loop'
AssertionError: infinite loop
```

Also see screenshot:
![screenshot from 2018-03-07 18-29-56](https://user-images.githubusercontent.com/2007393/37107930-f51fb59e-2235-11e8-9ffc-c058e5f35428.png)

**Comment by martin-sucha** [comment]
Another example. Seems like it occurs when the first player is tail chasing another one that dies.
In the following situation the (now dead) snake was going up, the yellow one to the right.
![screenshot from 2018-03-07 19-03-25](https://user-images.githubusercontent.com/2007393/37109488-620b4e6c-223a-11e8-880a-fc877d07127e.png)

**Comment by dn0** [comment]
@martin-sucha Thank you very much for the bug report. I could indeed reproduce the bug by simulating the behavior you've described (a snake that is tail chased dies).
